name: Deploy to Apigee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Install jq
      run: sudo apt-get install jq

    - name: Create target directory
      run: mkdir -p target

    - name: Zip project files
      run: zip -r ./target/crud_sample.zip .

    - name: List workspace files
      run: ls -al

    - name: Create new API proxy revision
      env:
        APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        APIGEE_TOKEN: ${{ secrets.APIGEE_TOKEN }}
      run: |
        response=$(curl -sS -X POST -w "\nHTTP_STATUS:%{http_code}" \
          -H "Authorization: Bearer $APIGEE_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./target/crud_sample.zip \
          "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/apis/crud_sample/revisions")
        echo "Response: $response"
        http_status=$(echo "$response" | grep -oP "HTTP_STATUS:\K\d+")
        response_body=$(echo "$response" | sed '/HTTP_STATUS:\d\+$/d')
        echo "HTTP status: $http_status"
        echo "Response body: $response_body" > create_revision_response.json
        revision=$(jq -r '.revision' create_revision_response.json)
        echo "revision=$revision" >> $GITHUB_ENV
        
    - name: Print deploy_revision_response.json content
      run: cat deploy_revision_response.json
