name: Deploy to Apigee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Create target directory
      run: mkdir -p target

    - name: Zip project files
      run: zip -r ./target/crud_sample.zip .

    - name: Install jq
      run: sudo apt-get install jq

    - name: Create new API proxy revision
      env:
        APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        APIGEE_TOKEN: ${{ secrets.APIGEE_TOKEN }}
      run: |
        response=$(curl -X POST \
          -H "Authorization: Bearer $APIGEE_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./target/crud_sample.zip \
          "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/apis/crud_sample/revisions")
        revision=$(echo "$response" | jq -r '.revision')
        echo "revision=$revision" >> $GITHUB_ENV

    - name: Deploy new API proxy revision
      env:
        APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        APIGEE_ENV: ${{ secrets.APIGEE_ENV }}
        APIGEE_TOKEN: ${{ secrets.APIGEE_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $APIGEE_TOKEN" \
          "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/apis/crud_sample/revisions/$revision/deployments?override=true"
