name: Apigee CI/CD

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Apigee Tool
      run: npm install -g apigeetool

    - name: Deploy to Apigee
      env:
        APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        APIGEE_ENV: ${{ secrets.APIGEE_ENV }}
        APIGEE_TOKEN: ${{ secrets.APIGEE_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $APIGEE_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./target/crud_sample.zip \
          "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/apis?name=crud_sample&action=deploy&override=true"

