name: Apigee CI/CD

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Mask Secrets
      run: |
        echo "::add-mask::${{ secrets.APIGEE_ORG }}"
        echo "::add-mask::${{ secrets.APIGEE_ENV }}"
        echo "::add-mask::${{ secrets.APIGEE_USER }}"
        echo "::add-mask::${{ secrets.APIGEE_PASS }}"

    - name: Deploy to Apigee
      env:
        APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
        APIGEE_ENV: ${{ secrets.APIGEE_ENV }}
        APIGEE_USER: ${{ secrets.APIGEE_USER }}
        APIGEE_PASS: ${{ secrets.APIGEE_PASS }}
      run: |
        curl -L https://github.com/apigee/apigeetool-node/archive/refs/tags/v0.8.0.tar.gz -o apigeetool.tar.gz
        tar -xzf apigeetool.tar.gz
        ./apigeetool-*/bin/apigeetool deployproxy -u $APIGEE_USER -p $APIGEE_PASS -o $APIGEE_ORG -e $APIGEE_ENV -n crud_sample -d .
