name: Deploy Apigee Proxy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.x' # Use a version compatible with the deploy.py script

    - name: Install dependencies
      run: pip install httplib2

    - name: Deploy to Apigee
      run: |
        python deploy.py -n $PROXY_NAME -o $APIGEE_ORG -h $APIGEE_HOST -d . -e $APIGEE_ENV -u "$APIGEE_USERNAME:$APIGEE_PASSWORD"
      env:
        APIGEE_USERNAME: ${{ secrets.APIGEE_USERNAME }}
        APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}
        APIGEE_ORG: microboost
        APIGEE_ENV: eval
        APIGEE_HOST: https://api.enterprise.apigee.com
        PROXY_NAME: crud_sample
        
